// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWOVYpS_IjkOmOPDL0uNWiAPgKkGA3bKk',
    appId: '1:240196716004:web:fee1476c4a71f4e598b3f1',
    messagingSenderId: '240196716004',
    projectId: 'taxi-b26be',
    authDomain: 'taxi-b26be.firebaseapp.com',
    storageBucket: 'taxi-b26be.appspot.com',
    measurementId: 'G-CKVKEV52VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrQ8Do-m70r_11b-uThNPAEiqpl6tEr00',
    appId: '1:240196716004:android:2e82e2b5cb6d9f4598b3f1',
    messagingSenderId: '240196716004',
    projectId: 'taxi-b26be',
    storageBucket: 'taxi-b26be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmZXO_8IyxjHinzjTc0lvRHBOlWJ1sN2w',
    appId: '1:240196716004:ios:d1f095f3b04f258798b3f1',
    messagingSenderId: '240196716004',
    projectId: 'taxi-b26be',
    storageBucket: 'taxi-b26be.appspot.com',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmZXO_8IyxjHinzjTc0lvRHBOlWJ1sN2w',
    appId: '1:240196716004:ios:f727cb750cef940e98b3f1',
    messagingSenderId: '240196716004',
    projectId: 'taxi-b26be',
    storageBucket: 'taxi-b26be.appspot.com',
    iosBundleId: 'com.example.taxiApp.RunnerTests',
  );
}
